# Generated by Django 5.0.1 on 2024-10-28 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_rating_product_rating_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_ratings',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
